export const environment = {
  production: true,
  bearer: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYzdmYTI1YjlmZTVlYjc0YWU4ODZiZmNjZGYzODY5NCIsInN1YiI6IjYxOTZmZmMxMTQ5NTY1MDA4ZmY4MzU3OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.OY-Pr_NWxGDJ9vBYXmo3W3Mp3tYl7JcD4kVmofjIodY'
};
